# Generated by Django 5.0.3 on 2024-03-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_postcategory_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default=111, upload_to='post/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.ImageField(upload_to='destination/'),
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
