# Generated by Django 5.0.3 on 2024-03-15 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_post_category_post_thumbnail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='bedrooms',
            new_name='bedroom',
        ),
    ]
